# Generated by Django 5.1.2 on 2024-10-19 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_city_condition_language_publishing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitab', 'verbose_name_plural': 'Kitablar'},
        ),
        migrations.AddField(
            model_name='book',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.city', verbose_name='Şəhər'),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.condition', verbose_name='Kitab Vəziyyəti'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='', verbose_name='Açıqlama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.language', verbose_name='Kitab Dili'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Kitab Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publishing', verbose_name='Nəşriyyat'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_books', to='books.category', verbose_name='Alt Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Sıra'),
        ),
    ]
