# Generated by Django 5.1.2 on 2024-10-27 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_emoji_code_alter_book_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['order'], 'verbose_name': 'Vəziyyət', 'verbose_name_plural': 'Vəziyyət'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='book-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='emoji_code',
            field=models.CharField(blank=True, help_text='Emojinin HTML kodu yazılmalıdır və sadəcə paret kateqoriyalarda əlavə edilməlidir. (emojiguide.org)', max_length=9, null=True, verbose_name='Emoji Kodu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='books.category', verbose_name='Üst Kateqoriya'),
        ),
    ]
