# Generated by Django 5.1.2 on 2024-10-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_condition_options_book_cover_photo_book_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='İcazə'),
        ),
    ]
